[package]
name = "MediaClassifier"
version = "1.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
exif = { package = "kamadak-exif", version = "0.6" }
chrono = "0.4"
log = "0.4"
simplelog = "0.12"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
