[package]
name = "MediaClassifier"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
exif = { package = "kamadak-exif", version = "0.6" }
chrono = "0.4"
log = "0.4"
simplelog = "0.12"
anyhow = "1.0"

[dev-dependencies]
tempfile = "3"
